### ISSUE TITLE
NoMethodError #Users (Edit Profile)

### ISSUE THREAD

**Issue by kevbaker** [timothyf/EngineY#1]
= How to reproduce:
- Log into account ( I was using admin/admin)
- Click on "Edit Profile"
- You get the below error

= Error:
- /users/31/edit

NoMethodError in Users#edit

Showing app/views/users/_user_form.html.erb where line #38 raised:

undefined method `api_key' for #User:0xb56a0648

Extracted source (around line #38):

35:             <label for="last_name">Last Name:</label>
36:             <%= f.text_field :last_name, :class=>'input_field' %>
37:         </div>
38:         <div class="form_field">
39:             <label for="email">Email</label>
40:             <%= f.text_field :email, :class=>'input_field'  %>
41:         </div>

Trace of template inclusion: app/views/users/edit.html.erb

RAILS_ROOT: /home/deploy/enginey/enginey.github.kevbaker.master.20100223
Application Trace | Framework Trace | Full Trace

/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/attribute_methods.rb:260:in `method_missing'
/home/deploy/enginey/enginey.github.kevbaker.master.20100223/app/models/user.rb:447:in`api_is_enabled?'
/home/deploy/enginey/enginey.github.kevbaker.master.20100223/app/views/users/_user_form.html.erb:38:in `_run_erb_app47views47users47_user_form46html46erb_locals_object_user_form'
/home/deploy/enginey/enginey.github.kevbaker.master.20100223/app/views/users/_user_form.html.erb:2:in`_run_erb_app47views47users47_user_form46html46erb_locals_object_user_form'
/home/deploy/enginey/enginey.github.kevbaker.master.20100223/app/views/users/edit.html.erb:5:in `_run_erb_app47views47users47edit46html46erb'

**Comment by timothyf** [comment]
make sure that your migrations are up to date.  Try running rake db:migrate again.  There is a new migration that creates the api_key column.  From this error it sounds like your User model is missing that column.

**Comment by kevbaker** [comment]
All set
