### ISSUE TITLE
Error on Create User Profile

### ISSUE THREAD

**Issue by kevbaker** [timothyf/EngineY#2]
I used the below command to test the API for creating a user. It throws an error. The user is created in the database, but I am not able to login as the user.

Thoughts? 

curl http://enginey.dev1.api.otrsnetwork.info/users.xml -d "user[login]=monkeytest3&user[first_name]=Monkey&user[last_name]=Test3&user[email]=monkeytest3@missionvi.com&user[password]=Monkey123&user[password_confirmation]=Monkey123" -X post -u admin:admin

**Comment by timothyf** [comment]
Is the error thrown when creating the user or when you try to login as the user?  Can you provide details of the error that you see?
Also, run the API tests using: 
rake api_tests
and make sure that they all pass.  If you get any errors, let me know what they are.

**Comment by kevbaker** [comment]
All set
