### ISSUE TITLE
Get Users API filters not working..

### ISSUE THREAD

**Issue by kevbaker** [timothyf/EngineY#3]
The API is not returning a filtered list based on the given parameter. Curl command below. I logged the code at the point of the filter in the user controller, and checked the generated SQL in the log, it does not contain the parameter in the where clause.. 

Can you have a look?

Example curl command:
curl http:/myserverurl/users.json -X get -u admin:admin -d "api_key=MYIPKEY&user[login]=admin"

**Comment by timothyf** [comment]
You are specifying the filter fields incorrectly.   For examples, you should refer to test/api/users_test.rb

Instead of using user[login]=admin
you should only use the field names like:
login=admin

**Comment by kevbaker** [comment]
ok, great... that makes sense. Also is it possible to do the following:

login=MYLOGIN&password=MYPASSWORD

to get check the user and their login, the same way that a new session would work?

It'd be great to have the action check for the password filter, encrypt it as needed and pass it in to the user query to do the lookup. The password is obviously a little diff than other fields used for a filter.

**Comment by timothyf** [comment]
the password filter isn't implemented yet, but I can add that to my task list.

**Comment by kevbaker** [comment]
This is high priority.. let me know when you have it ready. Thanks Tim

**Comment by kevbaker** [comment]
This was one of the things that we added in our last push, all good now.
